<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\ActivitiesList;
use Illuminate\Support\Facades\DB;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('activitieslist')->insert([

            ["Name" => "Distribution des échantillons"],
            ["Name" => "Essai clinique"],
            ["Name" => "Mailing"],
            ["Name" => "Conférences"],
            ["Name" => "Tables rondes"],
            ["Name" => "Visites médicales"],
            ["Name" => "Publicité directe au consommateur"],
            ["Name" => "Publicité directe au consommateur en ligne"],
            ["Name" => "Publicité dans les revues"],
            ["Name" => "Générique (Médecins)"],
            ["Name" => "Générique (Patients)"],
            ["Name" => "Promotion numérique pour les médecins"],

        ]);

        DB::table('activityItems')->insert([

            ["Name" => "Nombre de médecins recevant des échantillons", "ActivityId" => 1],
            ["Name" => "Nombre d’échantillons donnés à chaque médecin", "ActivityId" => 1],
            ["Name" => "Nombre total d’échantillons distribués", "ActivityId" => 1],
            ["Name" => "Pourcentage des échantillons réellement donnés aux patients", "ActivityId" => 1],
            ["Name" => "Nombre moyen d’échantillons donnés par patient", "ActivityId" => 1],
            ["Name" => "Nombre total de patients ayant reçu un échantillon", "ActivityId" => 1],
            ["Name" => "Pourcentage des patients ayant reçu une prescription après usage de l’échantillon", "ActivityId" => 1],
            ["Name" => "Nombre total de patients obtenant une prescription", "ActivityId" => 1],
            ["Name" => "Pourcentage des patients prescrits sans échantillon", "ActivityId" => 1],
            ["Name" => "Nombre total de patients incrémentaux gagnés grâce aux échantillons", "ActivityId" => 1],
            ["Name" => "Valeur moyenne d’un patient incrémental en MAD", "ActivityId" => 1],
            ["Name" => "Revenus supplémentaires générés grâce aux patients incrémentaux", "ActivityId" => 1],
            ["Name" => "Coût unitaire d’un échantillon", "ActivityId" => 1],
            ["Name" => "Coût variable total", "ActivityId" => 1],
            ["Name" => "Coûts fixes du programme", "ActivityId" => 1],
            ["Name" => "Coût total du programme", "ActivityId" => 1],
            ["Name" => "Retour sur Investissement (ROI)", "ActivityId" => 1],
            ["Name" => "Nombre de médecins participant à l'étude", "ActivityId" => 2],
            ["Name" => "Nombre moyen de patients inscrits par médecin", "ActivityId" => 2],
            ["Name" => "Nombre total de patients inscrits", "ActivityId" => 2],
            ["Name" => "Pourcentage moyen de patients qui continuent le traitement après l'étude", "ActivityId" => 2],
            ["Name" => "Nombre de patients poursuivant le traitement après l'étude", "ActivityId" => 2],
            ["Name" => "Nombre de nouveaux patients traités par médecin grâce à l'étude", "ActivityId" => 2],
            ["Name" => "Nombre de patients incrémentaux obtenus grâce à l’étude", "ActivityId" => 2],
            ["Name" => "Valeur du revenu par patient incrémental", "ActivityId" => 2],
            ["Name" => "Ventes incrémentales générées", "ActivityId" => 2],
            ["Name" => "Coût variable par médecin", "ActivityId" => 2],
            ["Name" => "Coût fixe total de l’étude", "ActivityId" => 2],
            ["Name" => "Coût total du programme", "ActivityId" => 2],
            ["Name" => "Retour sur Investissement (ROI)", "ActivityId" => 2],
            ["Name" => "Nombre total de médecins ciblés par l’email", "ActivityId" => 3],
            ["Name" => "Pourcentage de médecins se rappelant avoir reçu l’email", "ActivityId" => 3],
            ["Name" => "Nombre de médecins ayant reçu et rappelé l’email", "ActivityId" => 3],
            ["Name" => "Pourcentage de médecins se rappelant de la marque et du message", "ActivityId" => 3],
            ["Name" => "Nombre de médecins se rappelant du produit et du message", "ActivityId" => 3],
            ["Name" => "Pourcentage de médecins prescrivant Prexige à de nouveaux patients après réception du message", "ActivityId" => 3],
            ["Name" => "Nombre de médecins prescrivant Prexige à la suite de l’email", "ActivityId" => 3],
            ["Name" => "Nombre moyen de nouveaux patients mis sous Prexige par médecin", "ActivityId" => 3],
            ["Name" => "Nombre de patients incrémentaux générés par l’email", "ActivityId" => 3],
            ["Name" => "Valeur du revenu par patient incrémental", "ActivityId" => 3],
            ["Name" => "Ventes incrémentales générées", "ActivityId" => 3],
            ["Name" => "Coût variable par email envoyé", "ActivityId" => 3],
            ["Name" => "Nombre moyen d’emails envoyés par médecin", "ActivityId" => 3],
            ["Name" => "Coût fixe total du programme", "ActivityId" => 3],
            ["Name" => "Coût total du programme", "ActivityId" => 3],
            ["Name" => "Retour sur Investissement (ROI)", "ActivityId" => 3],
            ["Name" => "Nombre de médecins participants à la conférence", "ActivityId" => 4],
            ["Name" => "Pourcentage de médecins ayant retenu le message", "ActivityId" => 4],
            ["Name" => "Nombre de médecins exposés au message", "ActivityId" => 4],
            ["Name" => "Pourcentage de médecins ayant changé positivement leur perception après la conférence", "ActivityId" => 4],
            ["Name" => "Nombre de médecins ayant une perception positive après le message", "ActivityId" => 4],
            ["Name" => "Pourcentage de ces médecins qui commencent à prescrire à de nouveaux patients", "ActivityId" => 4],
            ["Name" => "Nombre de médecins prescrivant à de nouveaux patients", "ActivityId" => 4],
            ["Name" => "Nombre moyen de nouveaux patients prescrits par médecin", "ActivityId" => 4],
            ["Name" => "Valeur d’ajustement KOL", "ActivityId" => 4],
            ["Name" => "Nombre de patients incrémentaux gagnés", "ActivityId" => 4],
            ["Name" => "Valeur de revenu générée par patient incrémental", "ActivityId" => 4],
            ["Name" => "Ventes incrémentales générées", "ActivityId" => 4],
            ["Name" => "Coût variable par médecin", "ActivityId" => 4],
            ["Name" => "Coût fixe du programme", "ActivityId" => 4],
            ["Name" => "Coût total du programme", "ActivityId" => 4],
            ["Name" => "Retour sur Investissement (ROI)", "ActivityId" => 4],
            ["Name" => "Nombre total de médecins participant", "ActivityId" => 5],
            ["Name" => "Nombre moyen de tables rondes assistées par médecin par an", "ActivityId" => 5],
            ["Name" => "Nombre total de contacts médecins", "ActivityId" => 5],
            ["Name" => "Nombre moyen de médecins par table ronde", "ActivityId" => 5],
            ["Name" => "Nombre total de tables rondes requises", "ActivityId" => 5],
            ["Name" => "% de médecins ayant changé positivement leur perception", "ActivityId" => 5],
            ["Name" => "Nombre de médecins ayant changé positivement leur perception", "ActivityId" => 5],
            ["Name" => "% de médecins influencés qui vont prescrire", "ActivityId" => 5],
            ["Name" => "Nombre de médecins prescrivant", "ActivityId" => 5],
            ["Name" => "Nombre moyen de nouveaux patients mis sous traitement par médecin", "ActivityId" => 5],
            ["Name" => "Nombre total de patients incrémentaux gagnés", "ActivityId" => 5],
            ["Name" => "Valeur du revenu par patient incrémental", "ActivityId" => 5],
            ["Name" => "Ventes incrémentales", "ActivityId" => 5],
            ["Name" => "Coût variable par table ronde", "ActivityId" => 5],
            ["Name" => "Coût fixe total du programme", "ActivityId" => 5],
            ["Name" => "Coût total du programme", "ActivityId" => 5],
            ["Name" => "Coût par contact médecin", "ActivityId" => 5],
            ["Name" => "Retour sur Investissement (ROI)", "ActivityId" => 5],
            ["Name" => "Nombre total de médecins ciblés par le représentant", "ActivityId" => 6],
            ["Name" => "Nombre moyen de visites (détails) par médecin", "ActivityId" => 6],
            ["Name" => "Nombre total de détails attendus", "ActivityId" => 6],
            ["Name" => "% de médecins se rappelant du message délivré lors de la visite", "ActivityId" => 6],
            ["Name" => "Nombre de médecins se rappelant du message transmis par le représentant", "ActivityId" => 6],
            ["Name" => "% de médecins prescrivant Prexige à de nouveaaprux patients ès avoir reçu le message", "ActivityId" => 6],
            ["Name" => "Nombre de médecins prescrivant Prexige à la suite de la visite", "ActivityId" => 6],
            ["Name" => "Nombre moyen de nouveaux patients mis sous Prexige par médecin", "ActivityId" => 6],
            ["Name" => "Nombre total de patients incrémentaux générés par la visite des représentants", "ActivityId" => 6],
            ["Name" => "Valeur du revenu par patient incrémental", "ActivityId" => 6],
            ["Name" => "Ventes incrémentales générées", "ActivityId" => 6],
            ["Name" => "Coût variable par représentant", "ActivityId" => 6],
            ["Name" => "Nombre total de représentants", "ActivityId" => 6],
            ["Name" => "Coût total du programme", "ActivityId" => 6],
            ["Name" => "Retour sur Investissement (ROI)", "ActivityId" => 6],
            ["Name" => "Nombre de consommateurs cibles pour la campagne", "ActivityId" => 7],
            ["Name" => "% d’audience cible atteinte par le plan média", "ActivityId" => 7],
            ["Name" => "Nombre de consommateurs atteints par la campagne", "ActivityId" => 7],
            ["Name" => "% de consommateurs atteints se rappelant de la campagne (taux de mémorisation)", "ActivityId" => 7],
            ["Name" => "Nombre de consommateurs se rappelant de la campagne", "ActivityId" => 7],
            ["Name" => "% de consommateurs se rappelant de la campagne DTC ayant consulté un médecin suite à l’exposition", "ActivityId" => 7],
            ["Name" => "Nombre de consommateurs consultant un médecin suite à la campagne", "ActivityId" => 7],
            ["Name" => "% de patients ayant consulté et recevant une prescription Prexige", "ActivityId" => 7],
            ["Name" => "Nombre de patients incrémentaux obtenus grâce à la campagne DTC", "ActivityId" => 7],
            ["Name" => "Valeur du revenu par patient incrémental", "ActivityId" => 7],
            ["Name" => "Ventes incrémentales générées", "ActivityId" => 7],
            ["Name" => "Dépenses médias (en MAD k)", "ActivityId" => 7],
            ["Name" => "Coûts de production, frais d’agence et autres (en MAD k)", "ActivityId" => 7],
            ["Name" => "Coût total du programme", "ActivityId" => 7],
            ["Name" => "Retour sur Investissement (ROI)", "ActivityId" => 7],
            ["Name" => "Population totale", "ActivityId" => 8],
            ["Name" => "Taux d’incidence de la maladie dans la population", "ActivityId" => 8],
            ["Name" => "Nombre total de patients souffrant de la maladie", "ActivityId" => 8],
            ["Name" => "% de patients déjà traités et satisfaits", "ActivityId" => 8],
            ["Name" => "Nombre de patients non traités ou insatisfaits", "ActivityId" => 8],
            ["Name" => "% de patients potentiels visés par la campagne en ligne", "ActivityId" => 8],
            ["Name" => "Nombre de patients ciblés par la campagne digitale", "ActivityId" => 8],
            ["Name" => "Nombre total de visites uniques sur le site", "ActivityId" => 8],
            ["Name" => "Taux d’efficacité d’atteinte des patients ciblés", "ActivityId" => 8],
            ["Name" => "% des visiteurs uniques qui passent un temps significatif sur le site", "ActivityId" => 8],
            ["Name" => "Nombre de visiteurs uniques obtenant assez d’informations pour agir", "ActivityId" => 8],
            ["Name" => "% des visiteurs uniques ayant consulté un médecin suite au message du site", "ActivityId" => 8],
            ["Name" => "Nombre de visiteurs uniques ayant consulté un médecin après la campagne", "ActivityId" => 8],
            ["Name" => "% des patients ayant reçu une prescription Prexige", "ActivityId" => 8],
            ["Name" => "Nombre de patients incrémentaux gagnés grâce à la campagne digitale", "ActivityId" => 8],
            ["Name" => "Valeur du revenu généré par patient incrémental", "ActivityId" => 8],
            ["Name" => "Ventes incrémentales gagnées grâce à la campagne digitale", "ActivityId" => 8],
            ["Name" => "Coût total du programme e-campagne", "ActivityId" => 8],
            ["Name" => "Retour sur Investissement (ROI) de la campagne digitale", "ActivityId" => 8],
            ["Name" => "Nombre de médecins ayant lu au moins une publication contenant une annonce produit", "ActivityId" => 9],
            ["Name" => "Nombre total d’insertions prévues sur l’année", "ActivityId" => 9],
            ["Name" => "Pourcentage des médecins lecteurs capables de se souvenir de la marque et du message après exposition", "ActivityId" => 9],
            ["Name" => "Nombre de médecins ayant mémorisé la marque et le message", "ActivityId" => 9],
            ["Name" => "Pourcentage des médecins ayant mémorisé la publicité qui commencent à prescrire le produit", "ActivityId" => 9],
            ["Name" => "Nombre de médecins ayant initié la prescription suite à l’exposition", "ActivityId" => 9],
            ["Name" => "Nombre moyen de nouveaux patients mis sous traitement par chaque médecin prescripteur", "ActivityId" => 9],
            ["Name" => "Nombre de patients incrémentaux gagnés grâce à la campagne presse", "ActivityId" => 9],
            ["Name" => "Revenu moyen généré par chaque nouveau patient traité", "ActivityId" => 9],
            ["Name" => "Ventes incrémentales générées par la campagne presse", "ActivityId" => 9],
            ["Name" => "Coûts d’achat d’espace publicitaire pour la campagne presse", "ActivityId" => 9],
            ["Name" => "Frais de création et de gestion de la campagne", "ActivityId" => 9],
            ["Name" => "Coût total de la campagne presse", "ActivityId" => 9],
            ["Name" => "Retour sur Investissement (ROI) de la campagne presse", "ActivityId" => 9],
            ["Name" => "Nombre de médecins exposés à l’activité", "ActivityId" => 10],
            ["Name" => "Pourcentage des médecins capables de se souvenir de la marque et du message", "ActivityId" => 10],
            ["Name" => "Nombre de médecins ayant mémorisé la marque et le message", "ActivityId" => 10],
            ["Name" => "Pourcentage des médecins ayant amélioré leur perception du produit", "ActivityId" => 10],
            ["Name" => "Nombre de médecins ayant amélioré leur perception", "ActivityId" => 10],
            ["Name" => "Pourcentage des médecins ayant changé de perception et prescrit à de nouveaux patients", "ActivityId" => 10],
            ["Name" => "Nombre de médecins ayant prescrit suite à l’activité", "ActivityId" => 10],
            ["Name" => "Nombre moyen de nouveaux patients traités par chaque médecin prescripteur", "ActivityId" => 10],
            ["Name" => "Nombre de patients incrémentaux gagnés grâce à l’activité", "ActivityId" => 10],
            ["Name" => "Revenu moyen généré par chaque nouveau patient traité", "ActivityId" => 10],
            ["Name" => "Ventes incrémentales générées par l’activité", "ActivityId" => 10],
            ["Name" => "Coût global de l’organisation et de la mise en oeuvre de l’activité", "ActivityId" => 10],
            ["Name" => "Retour sur Investissement (ROI)", "ActivityId" => 10],
            ["Name" => "Nombre de consommateurs exposés à l’activité", "ActivityId" => 11],
            ["Name" => "Pourcentage des consommateurs capables de se souvenir du message", "ActivityId" => 11],
            ["Name" => "Nombre de consommateurs ayant mémorisé le message", "ActivityId" => 11],
            ["Name" => "Pourcentage des consommateurs ayant consulté un médecin", "ActivityId" => 11],
            ["Name" => "Nombre de consultations générées suite au message", "ActivityId" => 11],
            ["Name" => "Pourcentage des consultations aboutissant à une prescription", "ActivityId" => 11],
            ["Name" => "Nombre total de patients incrémentaux", "ActivityId" => 11],
            ["Name" => "Revenu moyen généré par chaque nouveau patient", "ActivityId" => 11],
            ["Name" => "Ventes incrémentales générées", "ActivityId" => 11],
            ["Name" => "Coût global de l’organisation et de la mise en oeuvre de l’activité", "ActivityId" => 11],
            ["Name" => "Retour sur Investissement (ROI)", "ActivityId" => 11],
            ["Name" => "Nombre de médecins susceptibles de prescrire le produit", "ActivityId" => 12],
            ["Name" => "Pourcentage des médecins utilisant internet pour des informations professionnelles", "ActivityId" => 12],
            ["Name" => "Nombre de médecins cibles pouvant être atteints via internet", "ActivityId" => 12],
            ["Name" => "Nombre total de visites uniques sur le site", "ActivityId" => 12],
            ["Name" => "Taux d’efficacité sur les médecins cibles", "ActivityId" => 12],
            ["Name" => "Pourcentage de visiteurs uniques ayant interagi davantage avec le contenu", "ActivityId" => 12],
            ["Name" => "Nombre de médecins ayant passé suffisamment de temps sur le site pour être informés", "ActivityId" => 12],
            ["Name" => "Pourcentage des médecins informés ayant changé positivement leur perception du produit", "ActivityId" => 12],
            ["Name" => "Nombre de médecins ayant changé positivement leur perception", "ActivityId" => 12],
            ["Name" => "Pourcentage des médecins ayant changé leur perception et qui sont susceptibles de prescrire le produit", "ActivityId" => 12],
            ["Name" => "Nombre total de médecins prescrivant le produit suite à l’activité", "ActivityId" => 12],
            ["Name" => "Nombre moyen de nouveaux patients par médecin ayant prescrit le produit", "ActivityId" => 12],
            ["Name" => "Nombre total de patients incrémentaux gagnés via le site", "ActivityId" => 12],
            ["Name" => "Valeur moyenne de revenu par patient incrémental", "ActivityId" => 12],
            ["Name" => "Ventes incrémentales générées via le site", "ActivityId" => 12],
            ["Name" => "Coût total du programme e-digital", "ActivityId" => 12],
            ["Name" => "Retour sur Investissement (ROI)", "ActivityId" => 12]






        ]);
    }
}
